export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const SET_ACTIVE_FETCH_DATA = 'SET_ACTIVE_FETCH_DATA';